version: '2.0'

services:

  mssql:
    image: microsoft/mssql-server-linux:2017-latest
    restart: always
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: v48iqEkpXJ4eCQ9H
    ports:
      - '1401:1433'